/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myconsumptions;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author darkheart
 */
public class AddEditTVShowForm extends javax.swing.JFrame {
    
    Connection conn = null;    
    PreparedStatement pst = null;    
    int editRecID = 0;
    /**
     * Creates new form AddEditTVShowForm
     */
    public AddEditTVShowForm() {
        initComponents();
        conn = db.java_db();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();     
        setLocation(500, size.height/2 - getHeight()/2);          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_TVShowTitle = new javax.swing.JTextField();
        cal_dateTVShowStarted = new com.toedter.calendar.JDateChooser();
        cal_dateTVShowEnded = new com.toedter.calendar.JDateChooser();
        btn_saveTVShow = new javax.swing.JButton();
        btn_CancelTVShow = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TV Show Information");
        setPreferredSize(new java.awt.Dimension(490, 208));

        jLabel1.setText("Title");

        cal_dateTVShowStarted.setDateFormatString("yyyy-MM-dd");

        cal_dateTVShowEnded.setDateFormatString("yyyy-MM-dd");

        btn_saveTVShow.setText("Save");
        btn_saveTVShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveTVShowActionPerformed(evt);
            }
        });

        btn_CancelTVShow.setText("Cancel");
        btn_CancelTVShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelTVShowActionPerformed(evt);
            }
        });

        jLabel2.setText("Date Started");

        jLabel3.setText("Date Ended");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TVShowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_CancelTVShow)
                        .addGap(18, 18, 18)
                        .addComponent(btn_saveTVShow))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cal_dateTVShowEnded, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cal_dateTVShowStarted, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_TVShowTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cal_dateTVShowStarted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cal_dateTVShowEnded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CancelTVShow)
                    .addComponent(btn_saveTVShow))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveTVShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveTVShowActionPerformed
        // TODO add your handling code here:
        if(this.editRecID > 0){
            this.update_TVShowRecord();
        }else{
            this.insert_new_TVShowRecord();
        }
    }//GEN-LAST:event_btn_saveTVShowActionPerformed

    private void btn_CancelTVShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelTVShowActionPerformed
        // TODO add your handling code here:
        TVShows tvs = new TVShows();
        tvs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CancelTVShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditTVShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditTVShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditTVShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditTVShowForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditTVShowForm().setVisible(true);
            }
        });
    }

    // Insert new book Record
    public void insert_new_TVShowRecord(){
        try {
            String sql ="insert into TVShows " 
                        + "(TVShowTitle, TVShowDateStart,TVShowDateEnd) "
                        + "values (?,?,?)";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_TVShowTitle.getText());
            pst.setString(2,((JTextField)cal_dateTVShowStarted.getDateEditor().getUiComponent()).getText());
            pst.setString(3,((JTextField)cal_dateTVShowEnded.getDateEditor().getUiComponent()).getText() );            
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");

       }
       catch (Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       finally {
            try{                
                pst.close();
                //clearAll();
                TVShows tvs = new TVShows();
                tvs.setVisible(true);
                this.dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }            
        }         
    }    
    //Load Record to Form
    public void loadRecordToForm(Map data) throws ParseException{
        
        txt_TVShowTitle.setText( (String)data.get("TVShowTitle") );
        String dateStartInString = (String)data.get("TVShowStartingDate");
        
        String dateEndInString = (String)data.get("TVShowEndingDate");
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        java.util.Date TVShowStartingDate = sdf.parse(dateStartInString);
        java.util.Date TVShowEndingDate = sdf.parse(dateEndInString);


        cal_dateTVShowStarted.setDate(TVShowStartingDate);
        cal_dateTVShowEnded.setDate(TVShowEndingDate);
    }
    public static void delete_TVShowRecord(int tvshowID){
        if(tvshowID <=0){
            JOptionPane.showMessageDialog(null,"No Valid Record Selected");
        }
        int TVShowID = tvshowID;
        Connection conn = db.java_db();
                
        try {
            String sql ="DELETE FROM TVShows WHERE TVShowID = ?";
            
            try (PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setString(1,Integer.toString(TVShowID));
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data deleted successfully");
            }

       }
       catch (SQLException | HeadlessException e){
          
           JOptionPane.showMessageDialog(null,e);
       }
       finally {
            try{                
               
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }            
        }
    }   
    
    //update book record
    public void update_TVShowRecord(){
        if(this.editRecID <= 0){
            JOptionPane.showMessageDialog(null,"No Valid Record Selected");
        }
        int TVShowID = this.editRecID;        
        
        try {
            String sql ="UPDATE TVShows SET " 
                        + "TVShowTitle = ?"
                        + ",TVShowDateStart = ?"
                        + ",TVShowDateEnd = ?"
                        +"WHERE TVShowID = ?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_TVShowTitle.getText());
            pst.setString(2,((JTextField)cal_dateTVShowStarted.getDateEditor().getUiComponent()).getText());
            pst.setString(3,((JTextField)cal_dateTVShowEnded.getDateEditor().getUiComponent()).getText() );
            pst.setString(4,Integer.toString(TVShowID));
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");

       }
       catch (Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       finally {
            try{                
                pst.close();
                //clearAll();
                TVShows tvs = new TVShows();
                tvs.setVisible(true);
                this.dispose();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }            
        }         
        
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CancelTVShow;
    private javax.swing.JButton btn_saveTVShow;
    private com.toedter.calendar.JDateChooser cal_dateTVShowEnded;
    private com.toedter.calendar.JDateChooser cal_dateTVShowStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_TVShowTitle;
    // End of variables declaration//GEN-END:variables
}
