/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myconsumptions;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author darkheart
 */
public class Movies extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size  = toolkit.getScreenSize();
        //setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);      
        setLocation(500, size.height/2 - getHeight()/2);             
        conn = db.java_db();        
        this.loadList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_OpenMoviesForm = new javax.swing.JButton();
        btn_deleteMovie = new javax.swing.JButton();
        btn_editMovies = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Movies = new javax.swing.JTable();
        btn_loadMovies = new javax.swing.JButton();
        btn_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movies");
        setPreferredSize(new java.awt.Dimension(487, 387));

        btn_OpenMoviesForm.setText("Add");
        btn_OpenMoviesForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpenMoviesFormActionPerformed(evt);
            }
        });

        btn_deleteMovie.setText("Delete");
        btn_deleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteMovieActionPerformed(evt);
            }
        });

        btn_editMovies.setText("Edit");
        btn_editMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editMoviesActionPerformed(evt);
            }
        });

        tbl_Movies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Movies);

        btn_loadMovies.setText("Load");
        btn_loadMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadMoviesActionPerformed(evt);
            }
        });

        btn_Ok.setText("OK");
        btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_OpenMoviesForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_editMovies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_deleteMovie)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_loadMovies)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Ok)
                                .addGap(18, 18, 18))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_OpenMoviesForm)
                    .addComponent(btn_deleteMovie)
                    .addComponent(btn_editMovies))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_loadMovies)
                    .addComponent(btn_Ok))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OpenMoviesFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpenMoviesFormActionPerformed
        // TODO add your handling code here:
        AddEditMovieForm amvf = new AddEditMovieForm();
        amvf.editRecID = 0;
        amvf.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_OpenMoviesFormActionPerformed
    //Load Record function
    private void loadRecord(int MovieID ) {    
        
        if(MovieID < 0){
            JOptionPane.showMessageDialog(null, "No movie is Selected!");
        }
        
        String sql = "SELECT MovieID AS 'Movie ID', MovieTitle AS 'Movie Title', Date AS 'Date Watched' FROM Movies WHERE MovieID = ?";
        
        String MovieTitle = "";
        String DateWatched = "";        
        
        try{

            pst = conn.prepareStatement(sql);    
            pst.setInt(1, MovieID);
            rs = pst.executeQuery();
            //rs.getString(1);
            MovieTitle = rs.getString(2);
            DateWatched = rs.getString(3);            
            
            
            AddEditMovieForm mvform = new AddEditMovieForm();
            
            mvform.setVisible(true);
            mvform.editRecID = MovieID;
            
            Map<String, String> mymap = new HashMap<String, String>();
            mymap.put("MovieID", Integer.toString(MovieID) );
            mymap.put("MovieTitle", MovieTitle); 
            mymap.put("Date", DateWatched);            
            
            mvform.loadRecordToForm(mymap);
            
            this.dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "DB Error!");
            }
        }
        
        
        
    }   
    private void btn_deleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteMovieActionPerformed

    private void btn_editMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editMoviesActionPerformed
        // TODO add your handling code here:
        int selRow = 0;
        int MovieID = 0;
        

        selRow = tbl_Movies.getSelectedRow();
        MovieID = (int)tbl_Movies.getValueAt(selRow, 0);
        
        this.loadRecord(MovieID);        
    }//GEN-LAST:event_btn_editMoviesActionPerformed

    private void btn_loadMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadMoviesActionPerformed
        // TODO add your handling code here:
        this.loadList();
    }//GEN-LAST:event_btn_loadMoviesActionPerformed

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OkActionPerformed
        // TODO add your handling code here:
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ok;
    private javax.swing.JButton btn_OpenMoviesForm;
    private javax.swing.JButton btn_deleteMovie;
    private javax.swing.JButton btn_editMovies;
    private javax.swing.JButton btn_loadMovies;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Movies;
    // End of variables declaration//GEN-END:variables

    private void loadList() {
        String sql = "SELECT MovieID AS 'Movie ID', MovieTitle AS 'Movie Title', Date AS 'Date Watched' FROM Movies ORDER BY date(Date) DESC";

        try{

            pst = conn.prepareStatement(sql);           
            rs = pst.executeQuery();

            tbl_Movies.setModel(DbUtils.resultSetToTableModel(rs));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "DB Error!");
            }
        }        
    }
}
