/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myconsumptions;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author darkheart
 */
public class Movies extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size  = toolkit.getScreenSize();
        //setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);      
        setLocation(500, size.height/2 - getHeight()/2);             
        conn = db.java_db();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_OpenMoviesForm = new javax.swing.JButton();
        btn_deleteMovie = new javax.swing.JButton();
        btn_editMovies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movies");
        setPreferredSize(new java.awt.Dimension(487, 387));

        btn_OpenMoviesForm.setText("Add");
        btn_OpenMoviesForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OpenMoviesFormActionPerformed(evt);
            }
        });

        btn_deleteMovie.setText("Delete");
        btn_deleteMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteMovieActionPerformed(evt);
            }
        });

        btn_editMovies.setText("Edit");
        btn_editMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editMoviesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(btn_OpenMoviesForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editMovies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteMovie)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_OpenMoviesForm)
                    .addComponent(btn_deleteMovie)
                    .addComponent(btn_editMovies))
                .addContainerGap(328, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_OpenMoviesFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OpenMoviesFormActionPerformed
        // TODO add your handling code here:
        AddBookForm adf = new AddBookForm();
        adf.editRecID = 0;
        adf.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_OpenMoviesFormActionPerformed

    private void btn_deleteMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteMovieActionPerformed

    private void btn_editMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editMoviesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editMoviesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_OpenMoviesForm;
    private javax.swing.JButton btn_deleteMovie;
    private javax.swing.JButton btn_editMovies;
    // End of variables declaration//GEN-END:variables
}
